spring.application.name=EcoCycleTech
spring.datasource.url=jdbc:mysql://localhost:3306/ecocycletech?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8090
server.servlet.context-path=/ecoCycleTech
spring.config.import=optional:classpath:application-secret.properties
