spring.application.name=EcoCycleTech
spring.datasource.url=jdbc:mysql://localhost:3306/ecocycletech?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8090
server.servlet.context-path=/ecoCycleTech
paypal.client-id=AfvlBW4lz55pwiKfI8Ls-mBNP2zmEyJqWfF6SZLOw8hDPY1_UTnr-loZddLYuk-oBwamCVWL9dtTeooC
paypal.client-secret=ED5dbgcJK-rGC0KDqcwQpfBBml_PPi5t6HxTs8dL3xOy_j8N1Xb2fXzgg1OaaCKbGJ0xD5X0QIXLlbrd
paypal.mode = sandbox