spring.application.name=EcoCycleTech
spring.datasource.url=jdbc:mysql://localhost:3306/ecocycletech?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8090
server.servlet.context-path=/ecoCycleTech
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jackson.serialization.write-dates-as-timestamps=false


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aminshil69@gmail.com
spring.mail.password= nhrc xhwt yhij rite
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
twilio.account-sid=AC71f55fb0c3ae52fa0eadbce0a3d34490
twilio.auth-token=ddc89f0cf9c66e66d917c7fbdd87e84a
twilio.phone-number=+13163925260
app.bad-words=shit,crap,idiot,foo,bar


spring.mvc.format.date=iso
spring.mvc.format.time=iso
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

spring.jackson.default-property-inclusion=non_null


